version: "3.9"


services:
  db:
    container_name: db
    image: postgres:16-alpine3.19
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - dev_network
    ports:
      - "6000:5432"

  api:
    container_name: detector
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - db
    networks:
      - dev_network
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  dev_network:
