# Generated by Django 4.2 on 2024-04-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_frame_builder', '0002_vehicle_delete_vehicleplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
